create database customer_behavior;
use customer_behavior;
select * from customers;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customers 
GROUP BY gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id , purchase_amount
FROM customers
WHERE discount_applied = "yes" AND purchase_amount > 
( SELECT ROUND(AVG(purchase_amount),2) AS avg_puchase_amount
FROM customers);

-- Q3. Which are the top 5 products with the highest average review rating?
 SELECT category , review_rating
 FROM customers
 ORDER BY review_rating DESC
 Limit 5 ;
 
-- Q4. Compare the average Purchase Amount between Standard and Express Shipping.
SELECT ROUND(AVG(purchase_amount),2) AS avg_purchase_amount, shipping_type
FROM customers
WHERE shipping_type IN  ("Standard","Express")
GROUP BY shipping_type ;

-- Q5. Do subscribed customers spend more? Compare average spend , total revenue between subscribers and non-subscribers.
SELECT subscription_status ,COUNT(customer_id) AS total_customer, 
ROUND(AVG(purchase_amount),2) AS avg_purchase_amount ,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customers 
WHERE subscription_status IN ( "yes" , "no" )
GROUP BY subscription_status
ORDER BY avg_purchase_amount DESC, total_revenue DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = "yes" THEN 1 ELSE 0 END)/COUNT(*),2 ) AS discount_rate
FROM customers
GROUP BY item_purchased 
ORDER BY discount_rate DESC 
LIMIT 5 ;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
WITH customer_type AS(
SELECT customer_id ,
previous_purchases, 
 CASE
      WHEN previous_purchases = 1 THEN "New" 
      WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
      ELSE "Loyal"
      END AS customer_segment 
FROM customers
)SELECT customer_segment , COUNT(*) AS customer_count
FROM customer_type 
GROUP BY customer_segment
ORDER BY customer_count desc;

-- Q8. What are the top 3 most purchased products within each category? 
WITH most_purchased_item AS (
SELECT category , item_purchased ,COUNT(*) AS total_purchases,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC ) AS rank_no
FROM customers
GROUP BY category , item_purchased
)SELECT * FROM most_purchased_item
WHERE rank_no <= 3 ;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT  subscription_status , COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5 
GROUP BY subscription_status 
ORDER BY repeat_buyers DESC ;

-- Q10. What is the revenue contribution of each age group?
SELECT age , SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age 
ORDER BY total_revenue DESC;




